#!/usr/bin/python3

import argparse
import json
import logging

from helpers.utils import (
    db_connect_readonly,
    get_release_arches,
    get_stats_cache,
)

STAT_NUMPKGS = "numpkgs"
STAT_NUMPKGSPASS = "numpkgspass"
STAT_FAILRUNS = "failruns"
STAT_PASSRUNS = "passruns"


def success_count_for_release_and_arch(db, release, arch):
    """Return number of packages whose most recent migration-reference/0 run was a pass."""
    c = db.cursor()
    c.execute(
        "SELECT COUNT(*) FROM ("
        "  SELECT DISTINCT ON (package) exitcode"
        "  FROM result"
        "  WHERE release = %s AND arch = %s AND triggers = %s"
        "  ORDER BY package, run_id DESC"
        ") AS latest "
        "WHERE exitcode IN (0, 2, 8)",
        (release, arch, "migration-reference/0"),
    )
    return c.fetchone()[0]


def calc_stats():
    logger.debug("Connecting to autopkgtest db")
    db_con = db_connect_readonly()
    if not db_con:
        logger.debug("Unable to get DB con")
        exit(1)

    logger.debug("Getting release arches")
    release_arches = get_release_arches()

    data = {}
    for release in release_arches:
        data[release] = {}
        for arch in release_arches[release]:
            data[release][arch] = {
                STAT_NUMPKGS: 0,
                STAT_NUMPKGSPASS: 0,
                STAT_PASSRUNS: 0,
                STAT_FAILRUNS: 0,
            }

    logger.debug("Getting package count per arch")
    c = db_con.cursor()
    c.execute(
        "SELECT release, arch, COUNT(DISTINCT package) FROM result GROUP BY release, arch"
    )
    for release, arch, numpkgs in c.fetchall():
        if numpkgs > 1:
            try:
                data[release][arch][STAT_NUMPKGS] = numpkgs
            except KeyError:
                pass

    logger.debug("Getting pass info for packages")
    c.execute(
        "SELECT release, arch, "
        "       CASE WHEN exitcode IN (0,2,8) "
        "           THEN 'passruns' ELSE 'failruns' END exit, "
        "       COUNT(run_id) "
        "FROM result "
        "GROUP BY release, arch, exit"
    )
    for release, arch, key, numruns in c.fetchall():
        try:
            data[release][arch][key] = data[release][arch].get(key, 0) + numruns
        except KeyError:
            pass

    logger.debug("Collating stats")
    for release in release_arches:
        for arch in release_arches[release]:
            data[release][arch][STAT_NUMPKGSPASS] = success_count_for_release_and_arch(
                db_con, release, arch
            )

    return data


def make_submission(data, context):
    measurement = "autopkgtest_package_stats"
    out = []
    for release in data:
        for arch in data[release]:
            release_arch_data = data[release][arch]
            for field in [
                STAT_NUMPKGS,
                STAT_NUMPKGSPASS,
                STAT_FAILRUNS,
                STAT_PASSRUNS,
            ]:
                m = {
                    "measurement": measurement,
                    "fields": {"count": release_arch_data[field]},
                    "tags": {
                        "release": release,
                        "arch": arch,
                        "stat": field,
                        "instance": context,
                    },
                }
                out.append(m)

            pass_percent = round(
                # avoid division by zero
                (
                    release_arch_data[STAT_NUMPKGSPASS]
                    / (release_arch_data[STAT_NUMPKGS] or 1)
                )
                * 100,
                2,
            )
            m = {
                "measurement": measurement,
                "fields": {"percentage": pass_percent},
                "tags": {
                    "release": release,
                    "arch": arch,
                    "instance": context,
                },
            }
            out.append(m)
    return out


def parse_args():
    arg_parser = argparse.ArgumentParser(
        description="Script to collect release and arch-specific data for "
        "passing or failing package tests."
    )
    arg_parser.add_argument("--debug", action="store_true", help="debug mode")
    return arg_parser.parse_args()


def main():
    cache_directory = get_stats_cache()
    cache_directory.mkdir(parents=True, exist_ok=True)

    data = calc_stats()
    logger.debug(f"Writing results to {cache_directory}")

    cache_file = cache_directory / "stats.json"
    cache_file.write_text(json.dumps(data))


if __name__ == "__main__":
    args = parse_args()
    logging.basicConfig(level=logging.DEBUG if args.debug else logging.INFO)
    logger = logging.getLogger("autopkgtest-success-stats")
    main()
