#!/usr/bin/python3
import json

from helpers.utils import get_autopkgtest_cloud_conf, get_indexed_packages

if __name__ == "__main__":
    cp = get_autopkgtest_cloud_conf()
    indexed_packages_fp = cp["web"]["indexed_packages"]

    indexed_packages = get_indexed_packages()
    with open(indexed_packages_fp, "w") as f:
        json.dump(indexed_packages, f)
